name: Firebase Hosting Deploy

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: Jemos-Labs/actions-jemoslabs/.github/workflows/firebase-hosting-deploy.yml@main
    with:
      firebase_project: ${{ vars.FIREBASE_PROJECT }}
    secrets: inherit
