name: Firebase Hosting Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: Jemos-Labs/actions-jemoslabs/.github/workflows/firebase-hosting-deploy.yml@main
    with:
      firebase_project: mi-firebase-terra
      node_version: "22"
    secrets: inherit