name: 🕵 Pull Request Automation

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

  pull_request_target:
    types: [labeled, unlabeled]

permissions:
  contents: write
  pull-requests: write
    
jobs:
  set-limit:
    runs-on: ubuntu-latest
    outputs:
      max_files: 

    steps:
      - name: Extract limit from PR labels
        id: extract
        run: |
          LIMIT=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name | select(startswith("limit:")) | split(":")[1]')
          echo "max_files=${LIMIT:-30}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ghs_JZ3Er9x16cAJmdjNbRxVfZHzM0UoiQ3uDSfo
          PR_NUMBER: 

  coverage-node:
    name: PR Validation
    uses: Jemos-Labs/actions-jemoslabs/.github/workflows/test-node.yaml@main
    with:
      ref: ${{ github.ref }}
      max_files: 
    secrets: inherit

  release:
    name: Create New Release
    uses: Jemos-Labs/actions-jemoslabs/.github/workflows/release-create.yaml@main
    if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' }}
    with:
      ref: ${{ github.ref }}
      head: ${{ github.event.pull_request.head.ref }}
      body: ${{ github.event.pull_request.body }}
    secrets: inherit
